name: deploy
on: 
  push:
    branches:
      - master 
jobs: 
  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - name: Set Node.js 12.x
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm test
  deploy:
    name: Deploy
    needs: unit-test
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - name: Set Node.js 12.x
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: compile
        run: npm run compile 
      - name: deploy 
        run: npm run deploy

